# ── config.yml ───────────────────────────────────────────────────────────────
default:                       # <- used when R_CONFIG_ACTIVE not set
  db:
    drv: SQLite
    dbname: data/db/pest.sqlite
    host: ""                  # not used by SQLite
    user: ""
    password: ""
  pool_min: 0                 # pool settings used by db_pool()
  pool_max: 5

dev:                           # example Postgres section
  db:
    drv: RPostgres::Postgres
    host: localhost
    port: 5432
    dbname: pest
    user: pest_rw
    password: !expr Sys.getenv("PEST_DB_PWD")   # read from env var
  pool_min: 1
  pool_max: 10

prod:
  db:
    drv: RPostgres::Postgres
    host: prod‑db.internal
    port: 5432
    dbname: pest
    user: pest_app
    password: !expr Sys.getenv("PEST_DB_PWD")   # never hard‑code secrets
  pool_min: 5
  pool_max: 20
